### ISSUE TITLE
Some thing about the csv converter

### ISSUE THREAD

**Issue by HansBambel** [HansBambel/Mobius_server#1]
Hey @dimstudio, 
some things I noticed in the converter:
`x = x[len(x) - 1].replace('.zip', '').replace('T', '-')`
--> `x = x[-1].replace('.zip', '')`
Here you remove the "T" from the timestamp, right? But if the user ID also contains a "T" this would also replace that one. Instead I would not replace it and instead parse the T here:
`session_datetime = datetime.strptime(recordingID, "%Y-%m-%d'T'%H:%M:%S.%f")`

Apart from that, really cool!

**Comment by dimstudio** [comment]
Good observation thanks
